# Build settings
markdown: redcarpet

# Site settings
title: "Matteo Borgato Blog"
description: "Il mondo visto dagli occhi miopi di un programmatore."
description_long: "Il mondo visto dagli occhi miopi di un programmatore che ama vivere all'estero."
keywords: "lavorare all'estero, vivere all'estero, sviluppatore web, programmatore, italiano a Londra, italiano a Amsterdam, colloquio di lavoro"

email: 
#blog logo
logo: "/assets/images/logoMB.png"
# blog cover
cover: "/assets/images/lavorando.jpg"

name: "Matteo Borgato"
author: "Matteo Borgato"
author_image: "/assets/images/matt.jpg"

paginate:	5

url: "http://blog.matteoborgato.com" 
baseurl: ""

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/borteo
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

# Outputting
permalink: /:title/
paginate_path: /page:num


sass:
  sass_dir: _sass
  style: :compressed

gems:
  - jekyll-sitemap
  - jekyll-paginate

exclude: ["gulp-tasks", "Gemfile", "Gemfile.lock", "README.md", "s3_website.yml", "node_modules", "gulpfile.js", "package.json"]
